packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@biomejs/biome': ^2.2.4
  '@prisma/client': ^6.16.2
  '@tanstack/react-router': 1.132.25
  '@tanstack/router-cli': ^1.132.21
  '@tanstack/router-devtools': ^1.132.25
  '@tanstack/router-vite-plugin': ^1.132.25
  '@types/fs-extra': ^11.0.4
  '@types/node': ^24.6.0
  '@types/prompts': ^2.4.9
  '@types/react': ^18.3.23
  '@types/react-dom': ^18.3.1
  '@vitejs/plugin-react': ^4.3.1
  arktype: ^2.0.0
  autoprefixer: ^10.4.21
  better-auth: ^1.3.23
  chalk: ^5.3.0
  fs-extra: ^11.2.0
  h3: ^1.13.0
  nitropack: ^2.12.6
  postcss: ^8.5.6
  prisma: ^6.16.2
  prompts: ^2.4.2
  react: ^18.3.1
  react-dom: ^18.3.1
  tailwindcss: ^3.4.0
  tailwind-merge: ^3.3.1
  tsx: ^4.19.2
  typescript: ^5.9.2
  vite: ^7.1.7

ignoredBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - esbuild
  - prisma
