packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@biomejs/biome': ^1.9.4
  '@prisma/client': ^5.7.0
  '@tanstack/react-router': 1.131.27
  '@tanstack/router-cli': ^1.58.0
  '@tanstack/router-devtools': ^1.58.0
  '@types/fs-extra': ^11.0.4
  '@types/node': ^22.17.2
  '@types/prompts': ^2.4.9
  '@types/react': ^18.3.5
  '@types/react-dom': ^18.3.0
  '@vitejs/plugin-react': ^4.3.1
  arktype: ^2.0.0
  autoprefixer: ^10.4.17
  better-auth: ^0.7.5
  chalk: ^5.3.0
  fs-extra: ^11.2.0
  h3: ^1.13.0
  nitropack: ^2.9.7
  postcss: ^8.4.33
  prisma: ^5.7.0
  prompts: ^2.4.2
  react: ^18.3.1
  react-dom: ^18.3.1
  tailwindcss: ^3.4.0
  tsx: ^4.19.2
  typescript: ^5.9.2
  vite: ^5.4.5

ignoredBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - esbuild
  - prisma
