name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

env:
  NODE_VERSION: '22'
  PNPM_VERSION: '10.15.0'

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Update dependencies
        run: pnpm update --latest

      - name: Database generation
        run: pnpm db:generate

      - name: Run tests after update
        run: pnpm test

      - name: Type check after update
        run: pnpm type-check

      - name: Lint after update
        run: pnpm lint

      - name: Build after update
        run: pnpm build

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "has-changes=false" >> $GITHUB_OUTPUT
            echo "No dependency updates available"
          else
            echo "has-changes=true" >> $GITHUB_OUTPUT
            echo "Dependencies updated"
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.has-changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: automated dependency updates'
          body: |
            ## Automated Dependency Updates
            
            This PR contains automated updates to project dependencies.
            
            ### Changes
            - Updated npm packages to their latest versions
            - Regenerated lock files
            - All tests pass with updated dependencies
            
            ### Verification
            - ✅ Type checking passed
            - ✅ Linting passed  
            - ✅ Tests passed
            - ✅ Build succeeded
            
            This PR was automatically created by the dependency update workflow.
          branch: chore/dependency-updates
          delete-branch: true
          assignees: ${{ github.repository_owner }}
          labels: |
            dependencies
            automated